#!/bin/bash
# Render the two node configs for the medium-change lab.
#
# Usage: generate-configs.sh [mesh-name] [netmon-enabled]
#
# `netmon-enabled` re-renders node-a with detection off. The test script uses
# that for its negative control: the same topology and the same move, with the
# only difference being the mechanism under test. A regression test that has
# never been seen to fail is a claim, not a test, so the suite proves the
# failure rather than asserting it from the changelog.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MC_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$MC_DIR/../.." && pwd)"
DERIVE_KEYS="$ROOT_DIR/testing/lib/derive_keys.py"
# Per-run, matching every other generator in the tree: compose bind-mounts
# this directory and the test script reads the npubs back after the containers
# are up, so a shared path lets a second run overwrite what a first is about
# to ping.
OUTPUT_DIR="$MC_DIR/generated-configs${FIPS_CI_NAME_SUFFIX:-}"

MESH_NAME="${1:-medium-change-$(date +%s)-$$}"
NETMON_ENABLED="${2:-true}"

primary="${MC_PRIMARY_PREFIX:-172.31.60}"
far="${MC_FAR_PREFIX:-172.31.62}"

mkdir -p "$OUTPUT_DIR"

keys_a="$(python3 "$DERIVE_KEYS" "$MESH_NAME" "a")"
keys_b="$(python3 "$DERIVE_KEYS" "$MESH_NAME" "b")"
nsec_a="$(echo "$keys_a" | awk -F= '/^nsec=/{print $2}')"
npub_a="$(echo "$keys_a" | awk -F= '/^npub=/{print $2}')"
nsec_b="$(echo "$keys_b" | awk -F= '/^nsec=/{print $2}')"
npub_b="$(echo "$keys_b" | awk -F= '/^npub=/{print $2}')"

write_config() {
    local output_file="$1" nsec="$2" peer_npub="$3" peer_alias="$4" \
          peer_addr="$5" netmon_block="$6"

    cat > "$output_file" <<EOF
# Generated by testing/medium-change/scripts/generate-configs.sh
node:
  identity:
    nsec: "$nsec"
$netmon_block
  retry:
    max_retries: 5
    base_interval_secs: 2

tun:
  enabled: true
  name: fips0
  mtu: 1280

dns:
  enabled: true

transports:
  udp:
    # Wildcard on purpose. A per-peer connected socket is only opened over a
    # wildcard-bound transport, and that socket is what this lab exercises.
    bind_addr: "0.0.0.0:2121"
    mtu: 1400

peers:
  - npub: "$peer_npub"
    alias: "$peer_alias"
    addresses:
      - transport: udp
        addr: "$peer_addr"
        priority: 1
EOF
}

if [ "$NETMON_ENABLED" = "true" ]; then
    netmon_a=$(cat <<'EOF'
  netmon:
    enabled: true
    poll_interval_secs: 5
    debounce_ms: 250
EOF
)
else
    netmon_a=$(cat <<'EOF'
  # Negative control: the detector is off, so nothing tells the node its
  # egress path moved and the connected socket stays pinned to the old one.
  netmon:
    enabled: false
EOF
)
fi

# node-a dials the far node through the router, so the route to it follows
# node-a's default route — the thing the suite moves.
write_config "$OUTPUT_DIR/node-a.yaml" "$nsec_a" "$npub_b" "node-b" \
    "${far}.20:2121" "$netmon_a"

# node-b is given node-a's *primary* address only. After the move that address
# is stale, which is the realistic shape: a configured peer whose path went
# away. Recovery by re-dial is therefore still possible here — and the suite
# distinguishes it from the fix by asserting session continuity, not merely
# that traffic eventually returns.
write_config "$OUTPUT_DIR/node-b.yaml" "$nsec_b" "$npub_a" "node-a" \
    "${primary}.10:2121" "  netmon:
    enabled: true"

cat > "$OUTPUT_DIR/npubs.env" <<EOF
NPUB_A=$npub_a
NPUB_B=$npub_b
EOF

echo "Generated configs in $OUTPUT_DIR (netmon on node-a: $NETMON_ENABLED)"
